import { compile } from 'json-schema-to-typescript'
import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '../../..')
const apiDir = path.resolve(rootDir, 'apps/api')
const webDir = path.resolve(rootDir, 'apps/web')

console.log('Fetching schema from Python code...')
try {
    // Using uv run to ensure we have the environment
    const cmd = 'uv run python dump_schema.py'
    const jsonOutput = execSync(cmd, { cwd: apiDir, encoding: 'utf-8' })
    const schema = JSON.parse(jsonOutput)

    console.log('Generating TypeScript types...')
    const ts = await compile(schema, 'ProtocolV2', {
      bannerComment: '/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript. \n * DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models in apps/api/app/protocol_v2.py\n * and run "npm run gen:types" in apps/web.\n */',
      style: {
          singleQuote: true
      },
      additionalProperties: false // Pydantic usually implies this for typed fields
    })

    const outFile = path.join(webDir, 'src/schema.ts')
    fs.writeFileSync(outFile, ts)
    console.log(`Wrote ${outFile}`)
} catch (e) {
    console.error('Error generating types:', e)
    process.exit(1)
}

