/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models in apps/api/app/protocol_v2.py
 * and run "npm run gen:types" in apps/web.
 */

export type ModelCallsUsed = number | null;
export type ModelCallsLimit = number | null;
export type ToolCallsUsed = number | null;
export type ToolCallsLimit = number | null;
export type Event = 'budget';
export type Name = string;
export type Type = string | null;
export type Visible = boolean | null;
export type Valuestring = string | null;
export type Definitionstring = string | null;
export type Commandstring = string | null;
/**
 * @minItems 1
 */
export type Objects = [string, ...string[]];
export type DeletedObjects = string[];
export type FailedObjects = RollbackError[] | null;
export type ObjectName = string;
export type Message = string;
export type Dialogs = string[] | null;
export type Expression = string;
export type Ok = boolean;
export type Labels = string[] | null;
export type Dialogs1 = string[] | null;
/**
 * @minItems 1
 */
export type Expressions = [string, ...string[]];
export type Expression1 = string;
export type Ok1 = boolean;
export type Value = number | null;
export type ValueString = string | null;
export type TempLabel = string | null;
export type Results = EvalNumericResult[];
export type Dialogs2 = string[] | null;
export type Command = string;
export type Ok2 = boolean;
export type Labels1 = string[] | null;
/**
 * @minItems 1
 */
export type Commands = [string, ...string[]];
export type Results1 = ExecGeogebraCommandResult[];
export type CreatedObjects = string[];
export type DeletedObjects1 = string[];
export type RolledBackObjects = string[] | null;
export type RollbackErrors = RollbackError[] | null;
export type Dialogs3 = string[] | null;
export type PresetApplied = ('geometry' | 'algebra') | null;
export type QualityWarnings = string[] | null;
export type Explanation = string;
export type Event1 = 'final';
export type Kind = 'frontend_tool';
export type ToolName = string;
export type ToolCallId = string;
export type Include = string[];
export type Objects1 = CanvasObjectSummary[];
export type Event2 = 'interrupt';
export type Name1 = string;
export type Event3 = 'node_end';
export type Name2 = string;
export type Event4 = 'node_start';
export type Id = string;
export type Text = string;
export type Done = boolean | null;
export type Plan = PlanItem[];
export type Event5 = 'plan_update';
export type ToolCallId1 = string;
export type ToolName1 = string;
export type Ok3 = boolean;
export type Event6 = 'run_end';
export type UserText = string;
export type RunId = string;
export type ThreadId = string;
export type ProtocolVersion = string;
export type LlmEnabled = boolean | null;
export type LlmModel = string | null;
export type LlmBaseUrl = string | null;
export type Event7 = 'run_start';
export type Locale = string;
export type Debug = boolean;
export type PlanMode = boolean;
export type IntentHint = {
  [k: string]: unknown;
} | null;
export type TextDelta = string;
export type Channel = ('content' | 'reasoning' | 'meta') | null;
export type Event8 = 'token';
export type ToolName2 = string;
export type ToolCallId2 = string;
export type Ok4 = boolean;
export type Event9 = 'tool_end';
export type ToolName3 = string;
export type ToolCallId3 = string;
export type Event10 = 'tool_start';
export type RunStreamEvent =
  | RunStartEvent
  | NodeStartEvent
  | NodeEndEvent
  | PlanUpdateEvent
  | TokenEvent
  | ToolStartEvent
  | InterruptEvent
  | ToolEndEvent
  | BudgetEvent
  | FinalEvent
  | RunEndEvent;

export interface ProtocolV2 {
  BudgetData?: BudgetData;
  BudgetEvent?: BudgetEvent;
  CanvasObjectSummary?: CanvasObjectSummary;
  DeleteObjectsInput?: DeleteObjectsInput;
  DeleteObjectsOutput?: DeleteObjectsOutput;
  EvalExpressionInput?: EvalExpressionInput;
  EvalExpressionOutput?: EvalExpressionOutput;
  EvalNumericInput?: EvalNumericInput;
  EvalNumericOutput?: EvalNumericOutput;
  EvalNumericResult?: EvalNumericResult;
  ExecGeogebraCommandResult?: ExecGeogebraCommandResult;
  ExecGeogebraCommandsInput?: ExecGeogebraCommandsInput;
  ExecGeogebraCommandsOutput?: ExecGeogebraCommandsOutput;
  FinalAnswer?: FinalAnswer;
  FinalData?: FinalData;
  FinalEvent?: FinalEvent;
  FrontendToolInterruptData?: FrontendToolInterruptData;
  GetCanvasStateInput?: GetCanvasStateInput;
  GetCanvasStateOutput?: GetCanvasStateOutput;
  InterruptEvent?: InterruptEvent;
  NodeEndData?: NodeEndData;
  NodeEndEvent?: NodeEndEvent;
  NodeStartData?: NodeStartData;
  NodeStartEvent?: NodeStartEvent;
  PlanItem?: PlanItem;
  PlanUpdateData?: PlanUpdateData;
  PlanUpdateEvent?: PlanUpdateEvent;
  ResumeCommand?: ResumeCommand;
  ResumeRequest?: ResumeRequest;
  RollbackError?: RollbackError;
  RunEndData?: RunEndData;
  RunEndEvent?: RunEndEvent;
  RunInput?: RunInput;
  RunStartData?: RunStartData;
  RunStartEvent?: RunStartEvent;
  RunStreamRequest?: RunStreamRequest;
  TokenData?: TokenData;
  TokenEvent?: TokenEvent;
  ToolEndData?: ToolEndData;
  ToolEndEvent?: ToolEndEvent;
  ToolResumePayload?: ToolResumePayload;
  ToolStartData?: ToolStartData;
  ToolStartEvent?: ToolStartEvent;
  UIContext?: UIContext;
  RunStreamEvent?: RunStreamEvent;
}
export interface BudgetData {
  model_calls_used?: ModelCallsUsed;
  model_calls_limit?: ModelCallsLimit;
  tool_calls_used?: ToolCallsUsed;
  tool_calls_limit?: ToolCallsLimit;
}
export interface BudgetEvent {
  event: Event;
  data: BudgetData;
}
export interface CanvasObjectSummary {
  name: Name;
  type?: Type;
  visible?: Visible;
  valueString?: Valuestring;
  definitionString?: Definitionstring;
  commandString?: Commandstring;
}
export interface DeleteObjectsInput {
  objects: Objects;
}
export interface DeleteObjectsOutput {
  deleted_objects?: DeletedObjects;
  failed_objects?: FailedObjects;
  dialogs?: Dialogs;
}
export interface RollbackError {
  object_name: ObjectName;
  message: Message;
}
export interface EvalExpressionInput {
  expression: Expression;
}
export interface EvalExpressionOutput {
  ok: Ok;
  labels?: Labels;
  error?: Error;
  dialogs?: Dialogs1;
}
export interface Error {
  [k: string]: unknown;
}
export interface EvalNumericInput {
  expressions: Expressions;
}
export interface EvalNumericOutput {
  results?: Results;
  dialogs?: Dialogs2;
}
export interface EvalNumericResult {
  expression: Expression1;
  ok: Ok1;
  value?: Value;
  value_string?: ValueString;
  temp_label?: TempLabel;
  error?: Error1;
}
export interface Error1 {
  [k: string]: unknown;
}
export interface ExecGeogebraCommandResult {
  command: Command;
  ok: Ok2;
  labels?: Labels1;
  error?: Error2;
}
export interface Error2 {
  [k: string]: unknown;
}
export interface ExecGeogebraCommandsInput {
  commands: Commands;
}
export interface ExecGeogebraCommandsOutput {
  results?: Results1;
  created_objects?: CreatedObjects;
  deleted_objects?: DeletedObjects1;
  rolled_back_objects?: RolledBackObjects;
  rollback_errors?: RollbackErrors;
  dialogs?: Dialogs3;
  preset_applied?: PresetApplied;
  quality_warnings?: QualityWarnings;
}
export interface FinalAnswer {
  explanation: Explanation;
  overlay_text?: OverlayText;
}
export interface OverlayText {
  [k: string]: unknown;
}
export interface FinalData {
  answer: FinalAnswer;
}
export interface FinalEvent {
  event: Event1;
  data: FinalData;
}
export interface FrontendToolInterruptData {
  kind?: Kind;
  tool_name: ToolName;
  tool_call_id: ToolCallId;
  input: Input;
}
export interface Input {
  [k: string]: unknown;
}
export interface GetCanvasStateInput {
  include?: Include;
}
export interface GetCanvasStateOutput {
  objects?: Objects1;
}
export interface InterruptEvent {
  event: Event2;
  data: FrontendToolInterruptData;
}
export interface NodeEndData {
  name: Name1;
}
export interface NodeEndEvent {
  event: Event3;
  data: NodeEndData;
}
export interface NodeStartData {
  name: Name2;
}
export interface NodeStartEvent {
  event: Event4;
  data: NodeStartData;
}
export interface PlanItem {
  id: Id;
  text: Text;
  done?: Done;
}
export interface PlanUpdateData {
  plan: Plan;
}
export interface PlanUpdateEvent {
  event: Event5;
  data: PlanUpdateData;
}
export interface ResumeCommand {
  resume: ToolResumePayload;
}
export interface ToolResumePayload {
  tool_call_id: ToolCallId1;
  tool_name: ToolName1;
  ok?: Ok3;
  output?: Output;
  error?: Error3;
}
export interface Output {
  [k: string]: unknown;
}
export interface Error3 {
  [k: string]: unknown;
}
export interface ResumeRequest {
  command: ResumeCommand;
}
export interface RunEndData {}
export interface RunEndEvent {
  event: Event6;
  data: RunEndData;
}
export interface RunInput {
  user_text: UserText;
}
export interface RunStartData {
  run_id: RunId;
  thread_id: ThreadId;
  protocol_version?: ProtocolVersion;
  llm_enabled?: LlmEnabled;
  llm_model?: LlmModel;
  llm_base_url?: LlmBaseUrl;
}
export interface RunStartEvent {
  event: Event7;
  data: RunStartData;
}
export interface RunStreamRequest {
  input: RunInput;
  ui_context?: UIContext;
}
export interface UIContext {
  locale?: Locale;
  debug?: Debug;
  plan_mode?: PlanMode;
  intent_hint?: IntentHint;
}
export interface TokenData {
  text_delta: TextDelta;
  channel?: Channel;
}
export interface TokenEvent {
  event: Event8;
  data: TokenData;
}
export interface ToolEndData {
  tool_name: ToolName2;
  tool_call_id: ToolCallId2;
  output: Output1;
  ok: Ok4;
  error?: Error4;
}
export interface Output1 {
  [k: string]: unknown;
}
export interface Error4 {
  [k: string]: unknown;
}
export interface ToolEndEvent {
  event: Event9;
  data: ToolEndData;
}
export interface ToolStartData {
  tool_name: ToolName3;
  tool_call_id: ToolCallId3;
  input: Input1;
}
export interface Input1 {
  [k: string]: unknown;
}
export interface ToolStartEvent {
  event: Event10;
  data: ToolStartData;
}
